### ISSUE TITLE
CEC broken with June packages

### ISSUE THREAD

**Issue by airend** [xbianonpi/xbian-package-cec#4]
This is probably a known issue, but `xbian-package-cec` beyond April doesn't work anymore (no remote support, or TV source switching). I reverted to `9.2.2.0-1-1430117049`, and it's working again. Is it because XBMC/Kodi needs to be recompiled against the recent library changes?

**Comment by Whoopie** [comment]
Install the debian package libxrandr2 and it's working again. libcec.so.2.0.1 is linked against libXrandr.so.2, but the library is missing.

**Comment by CurlyMoo** [comment]
What platform?

**Comment by Whoopie** [comment]
rpi2

**Comment by CurlyMoo** [comment]
Let's see if our auto build system works as expected and the new CEC package will show up in four hours.

**Comment by airend** [comment]
Thanks a lot, @Whoopie; indeed, that was the problem. I didn't even check `ldd`, assuming that something like `dh_shlibdeps` would take care of this. Anyway, @CurlyMoo, I'm confirming that `1434136799` fixes it for good (old RPi here).

**Comment by CurlyMoo** [comment]
I just love the automatic build system. I only had to do the commit. The rest was automated from building till deployment :+1:
